- name: Install java 8 preresequesits
  apt: name=python-software-properties

- name: Add Java 8 repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Agree to oracle license
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

- name: Install Java 8
  apt: name=oracle-java8-installer force=yes


- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present


- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state: present
    update_cache: yes


- name: Install Elasticsearch.
  apt: pkg=elasticsearch state=present

- name: Configure Elasticsearch
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  register: ESconfig

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

- name: enable and start elastic search
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
    masked: no

- name: Restart elastic search if we updated config file
  systemd:
    name: elasticsearch
    enabled: yes
    state: restarted
    masked: no
  when: ESconfig.changed

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300
